//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ilann
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ilann()
        {
            this.sirket_ilan = new HashSet<sirket_ilan>();
            this.basvuru = new HashSet<basvuru>();
        }
    
        public int id { get; set; }
        public string sirketadi { get; set; }
        public string ilanaciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sirket_ilan> sirket_ilan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<basvuru> basvuru { get; set; }
    }
}
