//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projeb.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projebEntities1 : DbContext
    {
        public projebEntities1()
            : base("name=projebEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<atama> atama { get; set; }
        public virtual DbSet<cv> cv { get; set; }
        public virtual DbSet<cvogrenci> cvogrenci { get; set; }
        public virtual DbSet<ogrenci> ogrenci { get; set; }
        public virtual DbSet<ogretmen> ogretmen { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<sirket> sirket { get; set; }
        public virtual DbSet<sirket_ilan> sirket_ilan { get; set; }
        public virtual DbSet<kabulformu> kabulformu { get; set; }
        public virtual DbSet<kabulformuogrenci> kabulformuogrenci { get; set; }
        public virtual DbSet<stajdef> stajdef { get; set; }
        public virtual DbSet<stajdefogrenci> stajdefogrenci { get; set; }
        public virtual DbSet<ilann> ilann { get; set; }
        public virtual DbSet<basvuru> basvuru { get; set; }
        public virtual DbSet<mesaj> mesaj { get; set; }
    }
}
