//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogretmen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ogretmen()
        {
            this.atama = new HashSet<atama>();
            this.mesaj = new HashSet<mesaj>();
        }
    
        public int id { get; set; }
        public string adsoyad { get; set; }
        public string tckimlik { get; set; }
        public string mail { get; set; }
        public string sifre { get; set; }
        public string bolum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atama> atama { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mesaj> mesaj { get; set; }
    }
}
