//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class sirket_ilan
    {
        public int id { get; set; }
        public int sirketid { get; set; }
        public int ilanid { get; set; }
    
        public virtual sirket sirket { get; set; }
        public virtual ilann ilann { get; set; }
    }
}
